# Do not resolve anything except what is configured above in this file
no-resolv

# Set fallback nameservers
server=1.1.1.1
server=1.0.0.1

# Add domain records
address=/*.test/127.0.0.1

# Enable logs
log-queries
# log-debug

# Log to STDOUT
log-facility=-
